### ISSUE TITLE
执行celery命令出错

### ISSUE THREAD

**Issue by crawler-plus** [SpiderClub/weibospider#116]
安装完依赖并且配置好mysql、redis之后，执行命令celery -A tasks.workers -Q login_queue,search_crawler worker -l info -c 1 报错，堆栈信息如下（我的python版本是3.5，celery版本是4.1.0）

Traceback (most recent call last):
  File "/usr/local/python3/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/python3/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/python3/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/python3/lib/python3.5/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/python3/lib/python3.5/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/python3/lib/python3.5/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/python3/lib/python3.5/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/local/python3/lib/python3.5/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/python3/lib/python3.5/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/usr/local/python3/lib/python3.5/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/usr/local/python3/lib/python3.5/site-packages/kombu/transport/base.py", line 125, in __getattr__
    raise AttributeError(key)
AttributeError: async

**Comment by yayays** [comment]
请问是如何解决的
