### ISSUE TITLE
执行任何py文件都会报错：No such file or directory: 'utils/emoji_ios6.json'

### ISSUE THREAD

**Issue by songyao1994** [SpiderClub/weibospider#118]
你好，我从GitHub导入最新项目到eclipse，然后上传到centos7配置运行，开启celery许可任务没问题，但是下一步执行python first_task_execution/login_first.py时一直会报这个错误，而且该路径下任何一个py文件都会报这个错误，我试着修改路径来解决这个错误，但是怎么改都还报错，请教这个问题如何解决？

`[root@node6 first_task_execution]# python login_first.py Traceback (most recent call last): File "login_first.py", line 6, in <module> from tasks import execute_login_task File "../tasks/__init__.py", line 1, in <module> from .comment import execute_comment_task File "../tasks/comment.py", line 2, in <module> from page_parse import comment File "../page_parse/comment.py", line 8, in <module> from utils import parse_emoji File "../utils/parse_emoji.py", line 20, in <module> sb_dict = load_emoji_map() File "../utils/parse_emoji.py", line 6, in load_emoji_map json_data = json.load(open(fn, encoding='utf-8')) FileNotFoundError: [Errno 2] No such file or directory: 'utils/emoji_ios6.json'`

1、我的问题在于执行first_task_execution文件夹下py文件的时候能够成功执行（云打码平台查到打码记录、数据库能够看到数据

2、我的到的结果是
![image](https://user-images.githubusercontent.com/35928118/44759050-6c7fd480-ab6a-11e8-830e-70d6d0dd1c91.png)

3、我的系统是CentOS7，我用的weibospider版本是GitHub实时同步的最新项目
![Uploading 屏幕快照 2018-08-29 上午9.06.16.png…]()
）

**Comment by ResolveWang** [comment]
`master`分支不保证你能稳定运行，有调试能力可以用它，如果只是需要用，建议下载[releases](https://github.com/SpiderClub/weibospider/releases)中的

**Comment by songyao1994** [comment]
已经解决这个问题了 ，把fn=‘'里面的相对路径改为本机的绝对路径即可。

**Comment by Tang0Tang** [comment]
> 
> 
> 已经解决这个问题了 ，把fn=‘'里面的相对路径改为本机的绝对路径即可。

请问是那个文件中的fn=‘’啊？

**Comment by Tang0Tang** [comment]
> 
> 
> 你好，我从GitHub导入最新项目到eclipse，然后上传到centos7配置运行，开启celery许可任务没问题，但是下一步执行python first_task_execution/login_first.py时一直会报这个错误，而且该路径下任何一个py文件都会报这个错误，我试着修改路径来解决这个错误，但是怎么改都还报错，请教这个问题如何解决？
> 
> `[root@node6 first_task_execution]# python login_first.py Traceback (most recent call last): File "login_first.py", line 6, in <module> from tasks import execute_login_task File "../tasks/__init__.py", line 1, in <module> from .comment import execute_comment_task File "../tasks/comment.py", line 2, in <module> from page_parse import comment File "../page_parse/comment.py", line 8, in <module> from utils import parse_emoji File "../utils/parse_emoji.py", line 20, in <module> sb_dict = load_emoji_map() File "../utils/parse_emoji.py", line 6, in load_emoji_map json_data = json.load(open(fn, encoding='utf-8')) FileNotFoundError: [Errno 2] No such file or directory: 'utils/emoji_ios6.json'`
> 
> 1、我的问题在于执行first_task_execution文件夹下py文件的时候能够成功执行（云打码平台查到打码记录、数据库能够看到数据
> 
> 2、我的到的结果是
> ![image](https://user-images.githubusercontent.com/35928118/44759050-6c7fd480-ab6a-11e8-830e-70d6d0dd1c91.png)
> ![image](https://user-images.githubusercontent.com/35928118/44759229-5de5ed00-ab6b-11e8-9ea5-1ce87c948b6a.png)
> 
> 3、我的系统是CentOS7，我用的weibospider版本是GitHub实时同步的最新项目
> ![image](https://user-images.githubusercontent.com/35928118/44759246-80780600-ab6b-11e8-8253-09a2eb922c26.png)

你好，请问最后问题是怎么解决的呢？我也遇到了同样的问题
