### ISSUE TITLE
配置好django的mysql的host，运行python admin/manage.py makemigrations时报错

### ISSUE THREAD

**Issue by mengguiyouziyi** [SpiderClub/weibospider#121]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
1、download master
2、vi config/spider.yml
3、vi admin/weibo_admin/settings.py
4、python admin/manage.py makemigrations
尽量把你的操作过程描述清楚，最好能够复现问题。
spider.yml
`
db:
    host: xx.xxx.xxx.112
    port: 3306
    user: xxx
    password: xxx
    db_name: weibo
    db_type: mysql

redis:
    host: xx.xxx.xxx.135
    port: xxx
    password: ''
    cookies: 1                   # store and fetch cookies
    # store fetched urls and results,so you can decide whether retry to crawl the urls or not
    urls: 2
    broker: 5                    # broker for celery
    backend: 6                   # backed for celery
    id_name: 8                   # user id and names，for repost info analysis. Could be safely deleted after repost tasks
    # expire_time (hours) for redis db2, if they are useless to you, you can set the value smaller
    expire_time: 48
    # redis sentinel for ha. if you neet it, just add sentinel host and port below the sentinel args,like this:
    ###############################
    #sentinel:                    #
    #    - host: 2.2.2.2          #
    #      port: 26379            #
    #    - host: 3.3.3.3          #
    #      port: 26379            #
    #                             #
    ###############################
    sentinel: ''
    master: ''             # redis sentinel master name, if you don't need it, just set master: ''
    socket_timeout: 5            # sockt timeout for redis sentinel, if you don't need it, just set master: ''
`

settings.py
`
 59 DATABASES = {
 60     'default': {
 61         'ENGINE': 'django.db.backends.mysql',
 62         'NAME': 'weibo',
 63         'USER': 'xxx',
 64         'PASSWORD': 'xxx',
 65         'HOST': 'xx.xxx.xxx.112',
 66         'PORT': '3306',
 67     }
 68 }
`
2.你期望的结果是什么？
期望不报错。
我settings.py中的host明明写的112，但是运行django的时候，就是135；
如果我改了112为其他的，运行django时，也会跟着变为对应的，只有112时会变成135。
非常诡异。

3.实际上你得到的结果是什么？
`
Traceback (most recent call last):
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 706, in __init__
    self.connect()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 932, in connect
    self._request_authentication()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 1152, in _request_authentication
    auth_packet = self._read_packet()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'xxx'@'xx.xxx.xxx.135' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "admin/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/models/base.py", line 1284, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/models/base.py", line 1359, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 913, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 219, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 322, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 49, in check_field
    field_type = field.db_type(self.connection)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 644, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 174, in data_types
    if self.features.supports_microsecond_precision:
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 53, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 385, in mysql_version
    with self.temporary_connection() as cursor:
  File "/search/chenguang/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 591, in temporary_connection
    cursor = self.cursor()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 706, in __init__
    self.connect()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 932, in connect
    self._request_authentication()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 1152, in _request_authentication
    auth_packet = self._read_packet()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/search/chenguang/meng/weibospider-master/.env/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1045, "Access denied for user 'xxx'@'xx.xxx.xxx.135' (using password: YES)")
`

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？
哪个版本的WeiboSpider：1.7.3
操作系统：centos 
是否有读：尚没有读

**Comment by uyplayer** [comment]
这个怎么解决呢？  我也碰到这样问题
