### ISSUE TITLE
使用master分支，sea

### ISSUE THREAD

**Issue by mrvx666** [SpiderClub/weibospider#124]
大大你好，非常喜欢你的项目，最近想从1.7.2切换到master分支，搜索任务无法运行，恳请大大解答

1.你是怎么操作的？
git clone master分支到本地，然后直接
celery -A tasks.workers -Q login_queue,search_crawler worker -l info --concurrency=1 -Ofair
运行，控制台运行正常，然后执行登陆
python3 first_task_execution/login_first.py，到此为止一切正常
然后运行搜索任务python3 first_task_execution/search_first.py，开始提示
The account has been expired，然后开始大面积报错。

2.你期望的结果是什么？
search_first任务正常执行，并成功写入数据库。

3.实际上你得到的结果是什么？

无法搜索任务，数据库为空。

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题])？
前段时间用的都是1.7.2，但是无奈稳定版太久不更新了，而且出现了爬取数据比预期数据少很多的情况，甚至一页只能获取到四五个数据，操作系统使用的是ubuntu 16.04 LTS，已经阅读过相关的Issues，没有查到类似情况的解决方案。

mrvx@mrvx:~/weibospider$ celery -A tasks.workers -Q login_queue,search_crawler worker -l info --concurrency=1 -Ofair
 
 -------------- celery@mrvx v4.1.0 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-4.4.0-85-generic-i686-with-Ubuntu-16.04-xenial 2018-09-07 16:48:09
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         weibo_task:0xb62b9b6c
- ** ---------- .> transport:   redis://:**@127.0.0.1:6379/5
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> login_queue      exchange=login_queue(direct) key=for_login
                .> search_crawler   exchange=search_crawler(direct) key=for_search_info

[tasks]
  . tasks.comment.crawl_comment_by_page
  . tasks.comment.crawl_comment_page
  . tasks.comment.execute_comment_task
  . tasks.dialogue.crawl_dialogue
  . tasks.dialogue.crawl_dialogue_by_comment_id
  . tasks.dialogue.crawl_dialogue_by_comment_page
  . tasks.dialogue.execute_dialogue_task
  . tasks.downloader.download_img_task
  . tasks.home.crawl_ajax_page
  . tasks.home.crawl_weibo_datas
  . tasks.home.execute_home_task
  . tasks.login.execute_login_task
  . tasks.login.login_task
  . tasks.praise.crawl_praise_by_page
  . tasks.praise.crawl_praise_page
  . tasks.praise.execute_praise_task
  . tasks.repost.crawl_repost_by_page
  . tasks.repost.crawl_repost_page
  . tasks.repost.execute_repost_task
  . tasks.search.execute_search_task
  . tasks.search.search_keyword
  . tasks.user.crawl_follower_fans
  . tasks.user.crawl_person_infos
  . tasks.user.crawl_person_infos_not_in_seed_ids
  . tasks.user.execute_user_task

[2018-09-07 16:48:10,047: INFO/MainProcess] Connected to redis://:**@127.0.0.1:6379/5
[2018-09-07 16:48:10,058: INFO/MainProcess] mingle: searching for neighbors
[2018-09-07 16:48:11,080: INFO/MainProcess] mingle: all alone
[2018-09-07 16:48:11,089: INFO/MainProcess] celery@mrvx ready.
[2018-09-07 16:48:14,534: INFO/MainProcess] Received task: tasks.login.login_task[8949bc11-55b1-4dbd-9be4-6ebfb3e2f0c1]  
[2018-09-07 16:48:24,551: INFO/MainProcess] Received task: tasks.login.login_task[b1d4521b-b529-410b-a254-4a85edf9220d]  
[2018-09-07 16:48:34,563: INFO/MainProcess] Received task: tasks.login.login_task[6aea175a-0247-41bc-b575-18af7c869514]  
2018-09-07 16:48:38 - other - INFO - Login successful! The login account is 13528612875
[2018-09-07 16:48:38,753: INFO/ForkPoolWorker-1] Login successful! The login account is 13528612875
[2018-09-07 16:48:38,756: INFO/ForkPoolWorker-1] Task tasks.login.login_task[8949bc11-55b1-4dbd-9be4-6ebfb3e2f0c1] succeeded in 24.221189369000058s: None
[2018-09-07 16:48:57,880: INFO/MainProcess] Received task: tasks.search.search_keyword[d19f3335-15d2-4287-b4d2-72c93afdd85f]  
2018-09-07 16:49:02 - other - INFO - Login successful! The login account is 13620883760
[2018-09-07 16:49:02,267: INFO/ForkPoolWorker-1] Login successful! The login account is 13620883760
[2018-09-07 16:49:02,272: INFO/ForkPoolWorker-1] Task tasks.login.login_task[b1d4521b-b529-410b-a254-4a85edf9220d] succeeded in 23.512898163000045s: None
2018-09-07 16:49:16 - other - INFO - Login successful! The login account is 17827463305
[2018-09-07 16:49:16,348: INFO/ForkPoolWorker-1] Login successful! The login account is 17827463305
[2018-09-07 16:49:16,351: INFO/ForkPoolWorker-1] Task tasks.login.login_task[6aea175a-0247-41bc-b575-18af7c869514] succeeded in 14.0774650379999s: None
2018-09-07 16:49:16 - crawler - INFO - We are searching keyword "地震"
[2018-09-07 16:49:16,353: INFO/ForkPoolWorker-1] We are searching keyword "地震"
2018-09-07 16:49:16 - crawler - INFO - the crawling url is http://s.weibo.com/weibo/%E5%9C%B0%E9%9C%87&region=custom:22:1000&scope=ori&suball=1&timescope=custom:2018-01-01-00:2018-01-15-23&page=1
[2018-09-07 16:49:16,354: INFO/ForkPoolWorker-1] the crawling url is http://s.weibo.com/weibo/%E5%9C%B0%E9%9C%87&region=custom:22:1000&scope=ori&suball=1&timescope=custom:2018-01-01-00:2018-01-15-23&page=1
2018-09-07 16:49:16 - crawler - WARNING - The account has been expired
[2018-09-07 16:49:16,356: WARNING/ForkPoolWorker-1] The account has been expired
[2018-09-07 16:49:34,518: WARNING/ForkPoolWorker-1] /home/mrvx/.local/lib/python3.5/site-packages/pymysql/cursors.py:166: Warning: (1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")
  result = self._query(query)
[2018-09-07 16:49:34,528: ERROR/ForkPoolWorker-1] Task tasks.search.search_keyword[d19f3335-15d2-4287-b4d2-72c93afdd85f] raised unexpected: InternalError('(pymysql.err.InternalError) (1054, "Unknown column \'weibo_data.weibo_img_path\' in \'field list\'")',)
Traceback (most recent call last):
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'weibo_data.weibo_img_path' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mrvx/.local/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mrvx/.local/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mrvx/weibospider/tasks/search.py", line 50, in search_keyword
    rs = WbDataOper.get_wb_by_mid(wb_data.weibo_id)
  File "/home/mrvx/weibospider/db/dao.py", line 174, in get_wb_by_mid
    return db_session.query(WeiboData).filter(WeiboData.weibo_id == mid).first()
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/mrvx/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/mrvx/.local/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'weibo_data.weibo_img_path' in 'field list'") [SQL: 'SELECT weibo_data.id AS weibo_data_id, weibo_data.weibo_id AS weibo_data_weibo_id, weibo_data.weibo_cont AS weibo_data_weibo_cont, weibo_data.weibo_img AS weibo_data_weibo_img, weibo_data.weibo_img_path AS weibo_data_weibo_img_path, weibo_data.weibo_video AS weibo_data_weibo_video, weibo_data.repost_num AS weibo_data_repost_num, weibo_data.comment_num AS weibo_data_comment_num, weibo_data.praise_num AS weibo_data_praise_num, weibo_data.uid AS weibo_data_uid, weibo_data.is_origin AS weibo_data_is_origin, weibo_data.device AS weibo_data_device, weibo_data.weibo_url AS weibo_data_weibo_url, weibo_data.create_time AS weibo_data_create_time, weibo_data.comment_crawled AS weibo_data_comment_crawled, weibo_data.repost_crawled AS weibo_data_repost_crawled, weibo_data.dialogue_crawled AS weibo_data_dialogue_crawled, weibo_data.praise_crawled AS weibo_data_praise_crawled \nFROM weibo_data \nWHERE weibo_data.weibo_id = %(weibo_id_1)s \n LIMIT %(param_1)s'] [parameters: {'weibo_id_1': '4196603482885035', 'param_1': 1}]
^C
worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)

**Comment by mrvx666** [comment]
`
URL = 'http://s.weibo.com/weibo/{}&region=custom:22:1000&scope=ori&suball=1&timescope=custom:{}:{}&page={}'
# Use this if results are too little
# URL = 'http://s.weibo.com/weibo/{}&nodup=1&page={}'
LIMIT = get_max_search_page() + 1


@app.task(ignore_result=True)
def search_keyword(keyword, keyword_id):
    time1 = get_time1()
    time2 = get_time2()
    crawler.info('We are searching keyword "{}"'.format(keyword))
    cur_page = 1
    encode_keyword = url_parse.quote(keyword)
    while cur_page < LIMIT:
        cur_url = URL.format(encode_keyword, time1, time2, cur_page)
        # current only for login, maybe later crawling page one without login
        search_page = get_page(cur_url, auth_level=2)
        if not search_page:
            crawler.warning('No search result for keyword {}, the source page is {}'.format(keyword, search_page))
            return
`


关于抓取微博少的问题，我已经对task/seach.py做了修改，使之能根据制定的时间和地点进行搜索，这个应该不算原因。日志说的好像是图片写入失败还是mysql数据库无法插入指定的字段。

**Comment by ResolveWang** [comment]
你查看一下你的账号是不是正常，Redis中有不有Cookie，是不是过期了

**Comment by thekingofcity** [comment]
先检查下数据库weibo_data表中有无weibo_img_path字段
PS. 虽然项目的表中有这个字段, 但是没有代码用到, 也没有任何一行是有内容的
