### ISSUE TITLE
我原来可以运行这个项目，但是我换了python3.7之后在运行celery -A tasks.workers worker -l info -c 1 -n worker1时出现错误

### ISSUE THREAD

**Issue by yjxxin** [SpiderClub/weibospider#131]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？

尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？

3.实际上你得到的结果是什么？

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by ResolveWang** [comment]
3.7目前还没支持哈，可能是部分第三方库的问题

**Comment by yjxxin** [comment]
我启动redis时运行src/redis-server命令时出现
10435:C 12 Oct 09:38:32.261 # Warning: no config file specified, using the default config. In order to specify a config file use src/redis-server /path/to/redis.conf
10435:M 12 Oct 09:38:32.262 * Increased maximum number of open files to 10032 (it was originally set to 1024).
10435:M 12 Oct 09:38:32.263 # Creating Server TCP listening socket *:6379: bind: Address already in use
这个错误怎么解决呢

**Comment by yjxxin** [comment]
我运行 sudo netstat -anp|grep 6379 
得到结果：tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      10828/redis-server 
哈怎么解除占用呢

**Comment by ResolveWang** [comment]
说明你的redis已经启动了

**Comment by yjxxin** [comment]
但是我已经用src/redis-server redis.conf启动时候，运行
>>> import redis
>>> r=redis.StrictRedis(host='127.0.0.1',port=6379,db=5,password='weibospider')
>>> s=redis.StrictRedis(host='127.0.0.1',port=6379,db=2,password='weibospider')
>>> r.flushdb()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangjiaxin/anaconda3/lib/python3.6/site-packages/redis/client.py", line 652, in flushdb
    return self.execute_command('FLUSHDB')
  File "/home/yangjiaxin/anaconda3/lib/python3.6/site-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/home/yangjiaxin/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/yangjiaxin/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/yangjiaxin/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 446, in connect
    self.on_connect()
  File "/home/yangjiaxin/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/home/yangjiaxin/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: Client sent AUTH, but no password is set
但我在redis.conf里面设置了密码
运行celery -A tasks.workers worker -l info -c 1 -n worker1也出现
[2018-10-12 09:48:15,138: ERROR/MainProcess] consumer: Cannot connect to redis://:**@127.0.0.1:6379/6: Client sent AUTH, but no password is set.
