### ISSUE TITLE
执行登录出错

### ISSUE THREAD

**Issue by jianzzz** [SpiderClub/weibospider#59]
版本：v1.7.2
操作：
1、source env.sh
2、python admin/manage.py runserver 0.0.0.0:8000
3、celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler,ajax_home_crawler,comment_crawler,comment_page_crawler,repost_crawler,repost_page_crawler worker -l info -c 1 &
4、python first_task_execution/login_first.py

已配置数据库、云打码
云打码已出现一次打码记录
但脚本执行出现以下问题：
[2017-12-31 16:51:02,851: ERROR/ForkPoolWorker-1] Task tasks.login.login_task[395b4991-9a63-4038-8dfc-3aabecf0cc8c] raised unexpected: MissingSchema("Invalid URL 'login_need_pincode': No schema supplied. Perhaps you meant http://login_need_pincode?",)
Traceback (most recent call last):
  File "/home/ubuntu/weibospider/.env/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/weibospider/.env/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/weibospider/tasks/login.py", line 12, in login_task
    get_session(name, password)
  File "/home/ubuntu/weibospider/login/login.py", line 229, in get_session
    rs_cont = session.get(url, headers=headers)
  File "/home/ubuntu/weibospider/.env/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/weibospider/.env/lib/python3.5/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/home/ubuntu/weibospider/.env/lib/python3.5/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/ubuntu/weibospider/.env/lib/python3.5/site-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/home/ubuntu/weibospider/.env/lib/python3.5/site-packages/requests/models.py", line 382, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'login_need_pincode': No schema supplied. Perhaps you meant http://login_need_pincode?

why?

**Comment by ResolveWang** [comment]
你好，首先感谢使用和反馈问题。
`2、python admin/manage.py runserver 0.0.0.0:8000`。从你的描述来看，你使用的可能不是1.7.2，因为1.7.2还没加入`admin`这个模块，请在[这里](https://github.com/SpiderClub/weibospider/releases) 选择你想下载的版本，master分支和dev分支目前还处于迭代开发的阶段，不建议使用。
使用有问题欢迎进一步交流和探讨。

**Comment by jianzzz** [comment]
我是git切换到branch v1.7.2上的。

**Comment by ResolveWang** [comment]
即使你是从master切换到v1.7.2,那么`python admin/manage.py runserver 0.0.0.0:8000`这个命令仍然不会成功
![image](https://user-images.githubusercontent.com/8018776/34474757-7e5b16e6-efbe-11e7-9009-d83b9f3ba5a9.png)

你再好好对照文档看看你的操作是否正确，据我所知，用1.7.2这个版本的同学都没有你这种情况。有问题再反馈吧。

**Comment by jianzzz** [comment]
ok，我明白了。关于切到1.7.2还能看到admin，是我加了-b误操作了。
另一个问题是，master跟v1.7.2的数据表能兼容吗？
也就是说，我想在1.7.2上测试程序收集结果，但操作结果使用master的web ui来读取。

**Comment by ResolveWang** [comment]
记得不清楚了，最近事情太多了，该项目暂时没做大的推进了。　`v1.7.2`之后应该加了一些字段，不过应该对于数据没啥影响。

**Comment by jianzzz** [comment]
1、python login_first.py
2、python user_first.py

**Comment by jianzzz** [comment]
1、python login_first.py
2、python user_first.py

------------------------------------
2018-01-02 14:09:53 - crawler - INFO - the crawling url is http://weibo.com/p/1005051195242865/info?mod=pedit_more
[2018-01-02 14:09:53,646: INFO/ForkPoolWorker-1] the crawling url is http://weibo.com/p/1005051195242865/info?mod=pedit_more
2018-01-02 14:09:53 - crawler - WARNING - no cookies in cookies pool, please find out the reason
[2018-01-02 14:09:53,650: WARNING/ForkPoolWorker-1] no cookies in cookies pool, please find out the reason
(WeiboSpider)root@jian-spider:/home/ubuntu/weibospider# 2018-01-02 14:09:54 - crawler - ERROR - failed to crawl http://weibo.com/p/1005051195242865/info?mod=pedit_more，here are details:(535, b'5.7.11 the behavior of this user triggered some restrictions to this account'), stack is   File "/home/ubuntu/weibospider/decorators/decorator.py", line 14, in time_limit
    return func(*args, **kargs)

[2018-01-02 14:09:54,293: ERROR/ForkPoolWorker-1] failed to crawl http://weibo.com/p/1005051195242865/info?mod=pedit_more，here are details:(535, b'5.7.11 the behavior of this user triggered some restrictions to this account'), stack is   File "/home/ubuntu/weibospider/decorators/decorator.py", line 14, in time_limit
    return func(*args, **kargs)

[2018-01-02 14:09:54,304: ERROR/ForkPoolWorker-1] list index out of range
[2018-01-02 14:09:54,304: ERROR/ForkPoolWorker-1] list index out of range
[2018-01-02 14:09:54,305: ERROR/ForkPoolWorker-1] list index out of range
[2018-01-02 14:09:54,324: INFO/MainProcess] Received task: tasks.user.crawl_follower_fans[49a1e5cb-240c-4b0d-a767-e1664574b74e]
2018-01-02 14:09:54 - crawler - INFO - the crawling url is http://weibo.com/p/1005051195242865/follow?relate=fans&page=1#Pl_Official_HisRelation__60
[2018-01-02 14:09:54,329: INFO/ForkPoolWorker-1] the crawling url is http://weibo.com/p/1005051195242865/follow?relate=fans&page=1#Pl_Official_HisRelation__60
2018-01-02 14:09:54 - crawler - WARNING - no cookies in cookies pool, please find out the reason
[2018-01-02 14:09:54,331: WARNING/ForkPoolWorker-1] no cookies in cookies pool, please find out the reason
2018-01-02 14:09:54 - crawler - ERROR - failed to crawl http://weibo.com/p/1005051195242865/follow?relate=fans&page=1#Pl_Official_HisRelation__60，here are details:(535, b'5.7.11 the behavior of this user triggered some restrictions to this account'), stack is   File "/home/ubuntu/weibospider/decorators/decorator.py", line 14, in time_limit
    return func(*args, **kargs)

[2018-01-02 14:09:54,958: ERROR/ForkPoolWorker-1] failed to crawl http://weibo.com/p/1005051195242865/follow?relate=fans&page=1#Pl_Official_HisRelation__60，here are details:(535, b'5.7.11 the behavior of this user triggered some restrictions to this account'), stack is   File "/home/ubuntu/weibospider/decorators/decorator.py", line 14, in time_limit
    return func(*args, **kargs)
