### ISSUE TITLE
celery 出现异步 问题

### ISSUE THREAD

**Issue by lizhuquan** [SpiderClub/weibospider#97]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
答：1）使用的是1.72版本，mysql 5.7, redis 3.29, centos 7, 相关配置已完毕,并正常启动（mysql,redis）；
        2）mysql 数据库已能正常通过native 工具查看，且weibo 数据库和相关表已完成建立（通过脚本）。
        3）在运行celery 之前，通过source env.sh 设置环境；启动mysql,redis(相应的配置redis.conf);
        4) 执行命令：celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler worker -l info -c 1
        5）出现异常，信息如下：
(WeiboSpider)[root@localhost weibospider-1.7.2]# celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler worker -l info -c 1
/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
Traceback (most recent call last):
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/kombu/transport/base.py", line 123, in __getattr__
    return self[key]
KeyError: 'async'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/weibospider-1.7.2/.env/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/root/weibospider-1.7.2/.env/lib/python3.5/site-packages/kombu/transport/base.py", line 125, in __getattr__
    raise AttributeError(key)
AttributeError: async

尽量把你的操作过程描述清楚，最好能够复现问题。
如上。
2.你期望的结果是什么？
   正常爬取微博数据。（已注册两个微博账号，正确设置login_info 和 seeds_ids 表）；
3.实际上你得到的结果是什么？
  出现异常。
4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题]
已经阅读。无相关答案。(https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by ResolveWang** [comment]
这个问题看起来是`celery`和`kombu`版本的冲突，你使用`pip freeze|grep kombu`看看它的版本，如果高于`4.1.0`请把它降级到`4.1.0`，具体可以看看[kombu 相关issue](https://github.com/celery/kombu/issues/870)

**Comment by lizhuquan** [comment]
已解决，将kombu 版本调至4.1.0 后正常。谢谢!

**Comment by CS0839** [comment]
老铁如何将kombu版本调至4.1.0

**Comment by ResolveWang** [comment]
@CS0839  
> pip uninstall kombu
> pip install kombu == 4.1.0
