### ISSUE TITLE
跟着到创建一个worker的时候出问题

### ISSUE THREAD

**Issue by CS0839** [SpiderClub/weibospider#98]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？

看着说明文档和视频一步一步来配置的，由于系统是新安装的，所以有很多指令都是缺什么下载什么的。

2.你期望的结果是什么？
期望创建一个worker

3.实际上你得到的结果是什么？
Traceback (most recent call last):
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/kombu/transport/base.py", line 123, in __getattr__
    return self[key]
KeyError: 'async'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wp/weibospider-1.7.2/.env/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/worker/worker.py", line 99, in __init__
[    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/home/wp/weibospider-1.7.2/.env/lib/python3.5/site-packages/kombu/transport/base.py", line 125, in __getattr__
    raise AttributeError(key)
AttributeError: async](url)

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题]
用的是weibospider-1.7.2；操作系统是ubunt16.04；有阅读本项目的常见问题

**Comment by ResolveWang** [comment]
感谢反馈，参照 issue #97
